name: letschat
description: A simple group chat application using flutter.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^1.1.2
  page_transition: ^1.1.7+6
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  flutter_icons: ^1.1.0

  emoji_picker: ^0.1.0
  intl: ^0.16.1
  flutter_keyboard_visibility: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:

  uses-material-design: true

  
  assets:
  - images/

